const API='https://flat-disk-51b0.sasaki-8ef.workers.dev',$=id=>document.getElementById(id),eventTools={'母の日':['スケジュール','アイテム別予測','カード同梱率','伝票発行クラウド'],'父の日':['スケジュール','予測・カード','伝票発行'],'敬老の日':['スケジュール','予測・カード','伝票発行'],'バレンタインデー':['スケジュール','予測・カード','伝票発行'],'ホワイトデー':['スケジュール','予測・カード','伝票発行'],'梨・柿':['出荷時期','受注締切','販売終了見込み','発注・出荷件数','梨掲示板'],'カニ':['せり情報','受注・発注締切','発注・出荷件数','カニ掲示板']};let rows=[],pendingImage='';
const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));const meta=r=>{try{return JSON.parse(r.memo||'{}')}catch{return {}}};
async function api(path,opt={}){const r=await fetch(API+path,{headers:{'Content-Type':'application/json'},cache:'no-store',...opt});if(!r.ok)throw new Error(await r.text());return r.json()}
async function load(){const d=await api('/orders/data');rows=(d.rows||[]).filter(r=>r.record_type==='tool_feedback').sort((a,b)=>(meta(b).createdAt||0)-(meta(a).createdAt||0));render()}
function card(r){const m=meta(r),cs=r.comments||[],done=m.status==='完了';return `<article class="post" data-id="${esc(r.id)}"><div class="postHead"><span class="badge ${done?'done':''}">${esc(m.status||'未確認')}</span><div class="meta"><b>${esc(m.summary||'件名なし')}</b><span>${esc(m.type||'要望')}｜${esc(m.event||'イベント未設定')}｜${esc(m.tool||'ツール未設定')}｜${esc(m.requester||'名前なし')}｜${new Date(m.createdAt||r.updated_at).toLocaleString('ja-JP')}</span></div></div><div class="body">${esc(m.details||'')}</div>${r.sheet_url?`<img class="postImage" src="${r.sheet_url}" alt="添付スクリーンショット">`:''}<div class="comments"><div>${cs.length?cs.map(c=>`<div class="comment"><b>${esc(c.author||'コメント')}</b>　${esc(c.text||c)}<br><small>${c.createdAt?new Date(c.createdAt).toLocaleString('ja-JP'):''}</small></div>`).join(''):'<div class="status">コメントはありません。</div>'}</div><div class="commentForm"><input placeholder="補足・返信を入力"><button>コメント追加</button></div></div></article>`}
function render(){const f=$('filter').value,list=f?rows.filter(r=>(meta(r).status||'未確認')===f):rows;$('list').innerHTML=list.length?list.map(card).join(''):'<div class="empty">投稿はまだありません。</div>';$('list').querySelectorAll('.post').forEach(el=>{const r=rows.find(x=>x.id===el.dataset.id),input=el.querySelector('.commentForm input');el.querySelector('.commentForm button').onclick=()=>comment(r,input.value.trim());const img=el.querySelector('.postImage');if(img)img.onclick=()=>window.open(img.src,'_blank')})}
async function comment(r,text){if(!text)return;const author=$('requester').value.trim()||localStorage.getItem('support-requester')||'担当者',comments=[...(r.comments||[]),{author,text,createdAt:Date.now()}];await api('/orders/rows/'+encodeURIComponent(r.id)+'/comments',{method:'PUT',body:JSON.stringify({comments})});await load()}
function compress(file){return new Promise((ok,no)=>{const rd=new FileReader();rd.onerror=no;rd.onload=()=>{const img=new Image();img.onerror=no;img.onload=()=>{const max=1600,s=Math.min(1,max/Math.max(img.width,img.height)),c=document.createElement('canvas');c.width=Math.round(img.width*s);c.height=Math.round(img.height*s);c.getContext('2d').drawImage(img,0,0,c.width,c.height);ok(c.toDataURL('image/jpeg',.82))};img.src=rd.result};rd.readAsDataURL(file)})}
$('event').innerHTML=Object.keys(eventTools).map(x=>`<option>${x}</option>`).join('');function syncTools(){$('tool').innerHTML=eventTools[$('event').value].map(x=>`<option>${x}</option>`).join('')}$('event').onchange=syncTools;syncTools();$('requester').value=localStorage.getItem('support-requester')||'';$('image').onchange=async()=>{const f=$('image').files[0];if(!f)return;pendingImage=await compress(f);$('preview').innerHTML=`<img src="${pendingImage}" alt="添付画像プレビュー">`};
$('send').onclick=async()=>{const requester=$('requester').value.trim(),summary=$('summary').value.trim(),details=$('details').value.trim();if(!requester||!summary||!details)return $('status').textContent='お名前・件名・詳しい内容を入力してください。';localStorage.setItem('support-requester',requester);const now=Date.now(),m={requester,event:$('event').value,tool:$('tool').value,type:$('type').value,summary,details,status:'未確認',createdAt:now,updatedAt:now},body={id:`tool-feedback|${now}|${Math.random().toString(36).slice(2,7)}`,date:new Date().toISOString().slice(0,10),partner:'改善要望:'+m.event+'｜'+m.tool,record_type:'tool_feedback',order_count:0,ship_count:0,sheet_url:pendingImage,memo:JSON.stringify(m),comments:[]};$('send').disabled=true;try{await api('/orders/rows',{method:'POST',body:JSON.stringify(body)});$('summary').value='';$('details').value='';$('image').value='';$('preview').innerHTML='';pendingImage='';await load();$('status').textContent='掲示板へ投稿しました。'}catch(e){$('status').textContent='投稿できませんでした。'}finally{$('send').disabled=false}};
document.querySelectorAll('.menu button').forEach(b=>b.onclick=()=>{document.querySelectorAll('.menu button').forEach(x=>x.classList.toggle('active',x===b));document.querySelectorAll('.view').forEach(v=>v.classList.toggle('active',v.id===b.dataset.view))});$('filter').onchange=render;$('reload').onclick=load;load().catch(()=>$('status').textContent='掲示板を読み込めませんでした。');
