const API='https://flat-disk-51b0.sasaki-8ef.workers.dev';
const EVENTS={mother:{label:'母の日',scheduleType:'mothers_day_schedule',month:5},father:{label:'父の日',scheduleType:'fathers_day_schedule',month:6},aged:{label:'敬老の日',scheduleType:'respect_for_aged_day_schedule',month:9},valentine:{label:'バレンタイン',scheduleType:'valentine_white_day_schedule',month:2},white:{label:'ﾎﾜｲﾄﾃﾞｰ',scheduleType:'white_day_schedule',month:3}};
const $=id=>document.getElementById(id),currentYear=new Date().getFullYear(),fmt=n=>Number(n||0).toLocaleString('ja-JP');
let activeEvent=new URLSearchParams(location.search).get('event')||'mother';if(!EVENTS[activeEvent])activeEvent='mother';
let scheduleRows=[],forecastRows=[],cardRows=[],invoiceRows=[],remoteIds=new Set(),scheduleYear=currentYear,scheduleMonth=EVENTS[activeEvent].month,forecastYear=currentYear,invoiceYear=currentYear,invoicePartner='福田屋',pendingDelete=null;
const scheduleSeeds=[['mday-notion-leaflet-sakane-drawer','2026-03-08','箪笥リーフレット（坂根屋分）','準備','','※カード付2,000／カードなし600',true],['mday-notion-card','2026-03-08','母の日カード','準備','','4,130',true],['mday-notion-leaflet-sakane','2026-03-08','上生リーフレット（坂根屋）','準備','坂根屋','2,100',true],['mday-notion-leaflet-fukudaya','2026-03-08','上生リーフレット（福田屋）','準備','福田屋','8,500',true],['mday-notion-leaflet-fukudaya-drawer','2026-03-08','箪笥リーフレット（福田屋分）','準備','福田屋','※カード付6,500／カードなし3,000',true],['mday-notion-pamphlet','2026-03-08','自社パンフ','準備','','3,750',true],['mday-notion-sakane-set','2026-03-17','坂根屋詰合せリーフレット','準備','坂根屋','※カード付300／カードなし150',true],['mday-notion-hibiya-set','2026-04-14','日比谷花壇パンフレットセット','準備','日比谷花壇','母700、OPP700、山陰1,000',true]].map(x=>({id:x[0],date:x[1],title:x[2],category:x[3],partner:x[4],details:x[5],done:x[6]}));
const forecastSeeds=[['forecast-mother-2026-fukudaya','福田屋','全体',21900],['forecast-mother-2026-sakaneya','坂根屋','全体',6150],['forecast-mother-2026-hibiya','日比谷花壇','全体',580],['forecast-mother-2026-rsl','RSL','全体',3756]].map(x=>({id:x[0],eventKey:'mother',year:2026,partner:x[1],item:x[2],forecast:x[3],note:'既存データから取り込み'}));
const cardSeed={id:'card-rate-mother-2025',eventKey:'mother',year:2025,partner:'全体',item:'母の日全体',total:30883,included:16943,excluded:13940};
async function api(path,opt={}){const r=await fetch(API+path,{cache:'no-store',headers:{'Content-Type':'application/json'},...opt});if(!r.ok)throw new Error(await r.text());return r.json()}
function esc(v){return String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))}
function yearsOf(...lists){return [...new Set([currentYear,currentYear-1,...lists.flat().map(x=>+x.year||+(x.date||'').slice(0,4)).filter(Boolean)])].sort((a,b)=>b-a)}
function parseSchedule(r){let m={};try{m=JSON.parse(r.memo||'{}')}catch{}return{id:r.id,date:r.date,title:m.title||'予定名未設定',category:['準備','集計','その他'].includes(m.category)?m.category:'準備',partner:m.partner||'',details:m.details||'',done:!!m.done}}
function scheduleBody(x){return{id:x.id,date:x.date,partner:EVENTS[activeEvent].label+(x.partner?':'+x.partner:''),record_type:EVENTS[activeEvent].scheduleType,order_count:0,ship_count:0,sheet_url:'',memo:JSON.stringify({title:x.title,category:x.category,partner:x.partner,details:x.details,done:x.done}),comments:[]}}
function parseForecast(r){let m={};try{m=JSON.parse(r.memo||'{}')}catch{}return{id:r.id,eventKey:m.eventKey,year:+m.year,partner:m.partner||m.label||'未設定',item:m.item||'全体',forecast:+m.forecast||+r.ship_count||0,note:m.note||''}}
function forecastBody(x){return{id:x.id,date:`${x.year}-01-01`,partner:`アイテム別予測:${EVENTS[x.eventKey].label}:${x.partner}:${x.item}`,record_type:'event_forecast',order_count:0,ship_count:x.forecast,sheet_url:'',memo:JSON.stringify(x),comments:[]}}
function parseCard(r){let m={};try{m=JSON.parse(r.memo||'{}')}catch{}const included=+m.included||+r.order_count||0,excluded=+m.excluded||+r.ship_count||0;return{id:r.id,eventKey:m.eventKey,year:+m.year,partner:m.partner||'全体',item:m.item||'母の日全体',total:+m.total||included+excluded,included,excluded}}
function cardBody(x){return{id:x.id,date:`${x.year}-01-01`,partner:`カード同梱率:${EVENTS[x.eventKey].label}:${x.partner}:${x.item}`,record_type:'event_card_rate',order_count:x.included,ship_count:x.excluded,sheet_url:'',memo:JSON.stringify(x),comments:[]}}
function parseInvoice(r){let m={};try{m=JSON.parse(r.memo||'{}')}catch{}return{id:r.id,eventKey:m.eventKey,year:+m.year,partner:m.partner||'',issueDate:m.issueDate||r.date,orderMemo:m.orderMemo||'',searchTitle:m.searchTitle||'',searchKey:m.searchKey||'',count:+m.count||0,shippingDate:m.shippingDate||''}}
function invoiceBody(x){return{id:x.id,date:x.issueDate,partner:`伝票発行:${EVENTS[x.eventKey].label}:${x.partner}`,record_type:'event_invoice_cloud',order_count:x.count,ship_count:0,sheet_url:'',memo:JSON.stringify(x),comments:[]}}
async function ensureSmallSeeds(all){if(activeEvent!=='mother')return;const seeds=[...scheduleSeeds.map(x=>[x,scheduleBody]),...forecastSeeds.map(x=>[x,forecastBody]),[cardSeed,cardBody]];for(const [x,fn] of seeds){if(all.some(r=>r.id===x.id))continue;try{await api('/orders/rows',{method:'POST',body:JSON.stringify(fn(x))})}catch{}}}
async function seedInvoicesInBackground(all){if(activeEvent!=='mother'||location.protocol==='file:')return;const missing=INVOICE_SEEDS.filter(x=>!all.some(r=>r.id===x.id));for(let i=0;i<missing.length;i+=8){await Promise.all(missing.slice(i,i+8).map(x=>api('/orders/rows',{method:'POST',body:JSON.stringify(invoiceBody(x))}).catch(()=>null)));await new Promise(r=>setTimeout(r,120))}}
async function loadAll(){renderEventTabs();if(location.protocol==='file:'){scheduleRows=activeEvent==='mother'?scheduleSeeds:[];forecastRows=activeEvent==='mother'?forecastSeeds:[];cardRows=activeEvent==='mother'?[cardSeed]:[];invoiceRows=activeEvent==='mother'?INVOICE_SEEDS:[];renderAll();return}let d=await api('/orders/data'),all=d.rows||[];await ensureSmallSeeds(all);d=await api('/orders/data');all=d.rows||[];remoteIds=new Set(all.map(r=>r.id));scheduleRows=all.filter(r=>r.record_type===EVENTS[activeEvent].scheduleType).map(parseSchedule);forecastRows=all.filter(r=>r.record_type==='event_forecast').map(parseForecast).filter(r=>r.eventKey===activeEvent);cardRows=all.filter(r=>r.record_type==='event_card_rate').map(parseCard).filter(r=>r.eventKey===activeEvent);const remoteInvoices=all.filter(r=>r.record_type==='event_invoice_cloud').map(parseInvoice).filter(r=>r.eventKey===activeEvent),seeds=activeEvent==='mother'?INVOICE_SEEDS:[];invoiceRows=[...remoteInvoices,...seeds.filter(s=>!remoteIds.has(s.id))];renderAll();seedInvoicesInBackground(all)}
