const API='https://flat-disk-51b0.sasaki-8ef.workers.dev';
const partners=['中村商店','浜勝商店','山根商店','梅吉水産'];
const $=id=>document.getElementById(id),currentYear=new Date().getFullYear();
let rows=[],active='すべて',selectedYear=currentYear,pendingImage='';
const esc=s=>String(s||'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
async function api(path,opt={}){const r=await fetch(API+path,{headers:{'Content-Type':'application/json'},...opt});if(!r.ok)throw new Error(await r.text());return r.json()}
function metadata(r){try{return JSON.parse(r.memo||'{}')}catch(e){return {}}}
function isCrabPost(r){return r.record_type==='crab_board_post'&&String(r.partner||'').startsWith('カニ掲示板:')}
function postYear(r){const m=metadata(r);return new Date(m.createdAt||r.date+'T00:00:00').getFullYear()}
function posts(){return rows.filter(isCrabPost).filter(r=>postYear(r)===selectedYear).filter(r=>active==='すべて'||metadata(r).partner===active).sort((a,b)=>(metadata(b).createdAt||0)-(metadata(a).createdAt||0))}
function formatDate(ms,date){const d=ms?new Date(ms):new Date(date+'T00:00:00');return new Intl.DateTimeFormat('ja-JP',{year:'numeric',month:'numeric',day:'numeric',hour:ms?'2-digit':undefined,minute:ms?'2-digit':undefined}).format(d)}
function initial(name){return String(name||'カ').replace('商店','').replace('水産','').slice(0,1)}
async function load(){const d=await api('/orders/data');rows=d.rows||[];render()}
function renderYears(){const years=new Set([currentYear,currentYear-1]);rows.filter(isCrabPost).forEach(r=>years.add(postYear(r)));const list=[...years].sort((a,b)=>b-a);if(!list.includes(selectedYear))selectedYear=currentYear;$('yearSelect').innerHTML=list.map(y=>`<option value="${y}" ${y===selectedYear?'selected':''}>${y}年</option>`).join('');$('quickYears').innerHTML=`<button type="button" data-year="${currentYear}" class="${selectedYear===currentYear?'active':''}">今年</button><button type="button" data-year="${currentYear-1}" class="${selectedYear===currentYear-1?'active':''}">去年</button>`;$('quickYears').querySelectorAll('button').forEach(b=>b.onclick=()=>{selectedYear=+b.dataset.year;renderYears();renderFeed()})}
function renderTabs(){$('tabs').innerHTML=['すべて',...partners].map(p=>`<button type="button" data-partner="${p}" class="${p===active?'active':''}">${p}</button>`).join('');$('tabs').querySelectorAll('button').forEach(b=>b.onclick=()=>{active=b.dataset.partner;renderTabs();renderFeed()})}
function renderFeed(){const list=posts();$('feed').innerHTML=list.length?list.map(r=>{const m=metadata(r),comments=r.comments||[];return `<article class="post card" data-id="${esc(r.id)}"><div class="postHead"><div class="avatar">${esc(initial(m.partner))}</div><div class="postMeta"><div class="partner">${esc(m.partner||'取引先')}</div><div class="time">${esc(formatDate(m.createdAt,r.date))}</div></div><button class="deleteButton" type="button" data-action="delete">削除</button></div>${m.text?`<div class="postText">${esc(m.text)}</div>`:''}${r.sheet_url?`<img class="postImage" src="${r.sheet_url}" alt="${esc(m.partner||'取引先')}の投稿画像">`:''}<div class="commentArea"><div class="commentList">${comments.length?comments.map(c=>`<div class="comment">${esc(typeof c==='string'?c:c.text||'')}</div>`).join(''):'<div class="status">コメントはありません。</div>'}</div><div class="commentComposer"><input class="commentInput" placeholder="コメントを入力"><button class="commentButton" type="button" data-action="comment">コメント</button></div></div></article>`}).join(''):`<div class="empty">${selectedYear}年の${active==='すべて'?'投稿':active+'の投稿'}はまだありません。</div>`;bindFeed()}
function render(){renderYears();renderTabs();renderFeed()}
function bindFeed(){$('feed').querySelectorAll('.post').forEach(card=>{const id=card.dataset.id;card.querySelector('[data-action="delete"]').onclick=()=>deletePost(id);card.querySelector('[data-action="comment"]').onclick=()=>addComment(id,card.querySelector('.commentInput').value.trim());const img=card.querySelector('.postImage');if(img)img.onclick=()=>{$('dialogImage').src=img.src;$('imageDialog').showModal()}})}
function setStatus(text){$('status').textContent=text;clearTimeout(setStatus.timer);setStatus.timer=setTimeout(()=>$('status').textContent='',3500)}
function clearComposer(){$('postText').value='';$('imageInput').value='';pendingImage='';$('imagePreview').innerHTML='';$('imagePreview').classList.add('hidden');$('removeImageBtn').classList.add('hidden')}
function compressImage(file){return new Promise((resolve,reject)=>{const rd=new FileReader();rd.onerror=reject;rd.onload=()=>{const img=new Image();img.onerror=reject;img.onload=()=>{const max=1400,scale=Math.min(1,max/Math.max(img.width,img.height)),w=Math.round(img.width*scale),h=Math.round(img.height*scale),canvas=document.createElement('canvas');canvas.width=w;canvas.height=h;canvas.getContext('2d').drawImage(img,0,0,w,h);resolve(canvas.toDataURL('image/jpeg',.82))};img.src=rd.result};rd.readAsDataURL(file)})}
$('partnerSelect').innerHTML=partners.map(p=>`<option>${p}</option>`).join('');
$('yearSelect').onchange=()=>{selectedYear=+$('yearSelect').value;renderYears();renderFeed()};
$('imageInput').onchange=async()=>{const file=$('imageInput').files[0];if(!file)return;try{setStatus('画像を準備中…');pendingImage=await compressImage(file);$('imagePreview').innerHTML=`<img src="${pendingImage}" alt="投稿前の画像プレビュー">`;$('imagePreview').classList.remove('hidden');$('removeImageBtn').classList.remove('hidden');setStatus('画像を追加しました。')}catch(e){setStatus('画像を読み込めませんでした。')}};
$('removeImageBtn').onclick=()=>{pendingImage='';$('imageInput').value='';$('imagePreview').innerHTML='';$('imagePreview').classList.add('hidden');$('removeImageBtn').classList.add('hidden')};
$('publishBtn').onclick=async()=>{const partner=$('partnerSelect').value,text=$('postText').value.trim();if(!text&&!pendingImage)return setStatus('文章または画像を追加してください。');$('publishBtn').disabled=true;try{setStatus('投稿中…');const now=Date.now(),date=new Date().toISOString().slice(0,10),id=`crab-board|${now}|${Math.random().toString(36).slice(2,7)}`,body={id,date,partner:'カニ掲示板:'+partner,record_type:'crab_board_post',order_count:0,ship_count:0,sheet_url:pendingImage,memo:JSON.stringify({partner,text,createdAt:now}),comments:[]};await api('/orders/rows',{method:'POST',body:JSON.stringify(body)});clearComposer();active=partner;selectedYear=currentYear;await load();setStatus('投稿しました。')}catch(e){setStatus('投稿できませんでした。画像を小さくして再度お試しください。')}finally{$('publishBtn').disabled=false}};
async function deletePost(id){const r=rows.find(x=>x.id===id);if(!r||!confirm('この投稿を削除しますか？'))return;try{await api('/orders/rows/'+encodeURIComponent(id),{method:'DELETE'});await load()}catch(e){setStatus('削除できませんでした。')}}
async function addComment(id,text){if(!text)return;const r=rows.find(x=>x.id===id);if(!r)return;const comments=[...(r.comments||[]),{text,createdAt:Date.now()}];try{await api('/orders/rows/'+encodeURIComponent(id)+'/comments',{method:'PUT',body:JSON.stringify({comments})});await load()}catch(e){setStatus('コメントを追加できませんでした。')}}
$('refreshBtn').onclick=async()=>{setStatus('更新中…');await load();setStatus('更新しました。')};$('closeImageDialog').onclick=()=>$('imageDialog').close();$('imageDialog').onclick=e=>{if(e.target===$('imageDialog'))$('imageDialog').close()};
(async()=>{try{await load()}catch(e){setStatus('共有データを読み込めませんでした。')}})();