(()=>{
const app=document.querySelector('.app'),header=document.querySelector('.header'),feed=document.getElementById('feed'),composer=document.querySelector('.composer'),publish=document.getElementById('publishBtn'),preview=document.getElementById('imagePreview'),remove=document.getElementById('removeImageBtn'),status=document.getElementById('status');if(!app||!header||!feed||!composer)return;
const switcher=document.createElement('nav');switcher.className='boardKinds';switcher.innerHTML='<button type="button" class="active" data-kind="post">投稿掲示板</button><button type="button" data-kind="material">資料掲示板</button>';header.after(switcher);
const columns=document.createElement('div');columns.className='boardColumns';composer.parentNode.insertBefore(columns,composer);columns.append(feed,composer);
let kind='post',busy=false;
function apply(){if(busy)return;busy=true;let shown=0;feed.querySelectorAll('.post').forEach(card=>{const material=!!card.querySelector('.postImage'),visible=kind==='material'?material:!material;card.classList.toggle('kindHidden',!visible);if(visible)shown++});const original=feed.querySelector(':scope > .empty'),generated=document.getElementById('kindEmpty');if(original)original.classList.toggle('kindHidden',kind==='material');const needs=!shown&&(kind==='material'||!original);if(needs&&!generated){const empty=document.createElement('div');empty.id='kindEmpty';empty.className='empty';empty.textContent=kind==='material'?'表示中の資料はまだありません。':'表示中の投稿はまだありません。';feed.appendChild(empty)}else if(!needs&&generated)generated.remove();busy=false}
function setKind(next){kind=next;app.dataset.kind=kind;switcher.querySelectorAll('button').forEach(b=>b.classList.toggle('active',b.dataset.kind===kind));composer.querySelector('.composerTitle').textContent=kind==='material'?'新しい資料':'新しい投稿';publish.textContent=kind==='material'?'資料を追加':'投稿する';document.getElementById('postText').placeholder=kind==='material'?'資料についての説明を入力してください。':'共有したい内容を入力してください。文字だけの投稿ができます。';if(kind==='post'&&!preview.classList.contains('hidden'))remove.click();apply()}
switcher.onclick=e=>{const b=e.target.closest('button');if(b)setKind(b.dataset.kind)};
publish.addEventListener('click',e=>{if(kind==='material'&&preview.classList.contains('hidden')){e.preventDefault();e.stopImmediatePropagation();status.textContent='資料の画像を追加してください。'}},true);
new MutationObserver(()=>apply()).observe(feed,{childList:true});
const style=document.createElement('style');style.textContent='.app{width:min(1180px,100%)}.boardKinds{display:flex;gap:8px;margin:0 0 12px}.boardKinds button{flex:1;min-height:44px;border:1px solid var(--line);border-radius:9px;background:#fff;padding:9px 13px;font:inherit;font-weight:900;cursor:pointer}.boardKinds button.active{background:var(--green);border-color:var(--green);color:#fff}.boardColumns{display:grid;grid-template-columns:minmax(0,1fr) 320px;gap:14px;align-items:start}.feed{grid-column:1;grid-row:1;max-height:720px;overflow-y:auto;padding-right:4px;scrollbar-gutter:stable}.composer{grid-column:2;grid-row:1;position:sticky;top:12px;margin:0}.kindHidden{display:none!important}.app[data-kind="post"] .imageButton,.app[data-kind="post"] #removeImageBtn,.app[data-kind="post"] #imagePreview{display:none!important}@media(max-width:760px){.boardColumns{grid-template-columns:1fr}.composer{grid-column:1;grid-row:1;position:static}.feed{grid-column:1;grid-row:2;max-height:none;overflow:visible;padding-right:0}}';document.head.appendChild(style);setKind('post');
})();
