const API='https://flat-disk-51b0.sasaki-8ef.workers.dev';
const partners=['中村商店','浜勝商店','山根商店','梅吉水産','かにの渡辺','山芳海産','前田水産'];
const $=id=>document.getElementById(id),currentYear=new Date().getFullYear();
let rows=[],view=new Date(currentYear,new Date().getMonth(),1),commentId='';
const esc=s=>String(s||'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
const fmt=d=>`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`;
async function api(path,opt={}){const r=await fetch(API+path,{headers:{'Content-Type':'application/json'},...opt});if(!r.ok)throw new Error(await r.text());return r.json()}
function meta(r){try{return JSON.parse(r.memo||'{}')}catch(e){return {price:r.memo||'',note:''}}}
function isAuction(r){return r.record_type==='crab_auction_price'&&String(r.partner||'').startsWith('カニせり情報:')}
function auctionRows(){return rows.filter(isAuction)}
async function load(){const d=await api('/orders/data');rows=d.rows||[];render()}
function availableYears(){const ys=new Set([currentYear,currentYear-1]);auctionRows().forEach(r=>ys.add(+String(r.date).slice(0,4)));return [...ys].filter(Boolean).sort((a,b)=>b-a)}
function renderYearControls(){const y=view.getFullYear(),years=availableYears();$('quickYears').innerHTML=`<button class="button ${y===currentYear?'active':''}" data-year="${currentYear}" type="button">今年</button><button class="button ${y===currentYear-1?'active':''}" data-year="${currentYear-1}" type="button">去年</button>`;$('quickYears').querySelectorAll('button').forEach(b=>b.onclick=()=>{view.setFullYear(+b.dataset.year);render()});$('yearSelect').innerHTML=years.map(v=>`<option value="${v}" ${v===y?'selected':''}>${v}年</option>`).join('')}
function render(){renderYearControls();renderCalendar();renderUpcoming()}
function renderCalendar(){const cal=$('calendar'),y=view.getFullYear(),m=view.getMonth(),today=fmt(new Date());$('monthLabel').textContent=`${y}年 ${m+1}月`;cal.innerHTML='';['日','月','火','水','木','金','土'].forEach(x=>cal.insertAdjacentHTML('beforeend',`<div class="dow">${x}</div>`));const start=new Date(y,m,1);start.setDate(1-start.getDay());for(let i=0;i<42;i++){const d=new Date(start);d.setDate(start.getDate()+i);const ds=fmt(d),same=d.getMonth()===m,day=document.createElement('div'),list=auctionRows().filter(r=>r.date===ds),priorDate=`${d.getFullYear()-1}-${ds.slice(5)}`,prior=same?auctionRows().filter(r=>r.date===priorDate):[];day.className=`day ${same?'':'other'} ${ds===today?'today':''}`;day.dataset.date=ds;const entries=list.slice(0,4).map(r=>{const mm=meta(r),count=(r.comments||[]).length;return `<div class="entry" data-id="${esc(r.id)}"><b>${esc(mm.partner||r.partner.replace('カニせり情報:',''))}</b><span class="price">${esc(mm.price||'価格未入力')}</span>${mm.note?`<span class="entryMemo">📝 ${esc(mm.note)}</span>`:''}<button class="commentBadge" type="button" title="コメント">💬${count}</button></div>`}).join('');const priorHtml=prior.length?`<div class="priorBox"><strong>${d.getFullYear()-1}年の同日</strong>${prior.map(r=>{const mm=meta(r);return `<div class="priorRow"><b>${esc(mm.partner||'取引先')}</b><span>${esc(mm.price||'価格未入力')}</span></div>`}).join('')}</div>`:'';day.innerHTML=`<div class="dayNum">${d.getDate()}</div>${entries}${list.length>4?`<div class="status">ほか${list.length-4}件</div>`:''}${priorHtml}`;if(same)day.onclick=e=>{const entry=e.target.closest('.entry');if(entry){const r=rows.find(x=>x.id===entry.dataset.id);if(e.target.closest('.commentBadge'))openComments(r);else editRow(r);e.stopPropagation()}else{clearForm();$('date').value=ds}};cal.appendChild(day)}}
function renderUpcoming(){const y=view.getFullYear(),list=auctionRows().filter(r=>+r.date.slice(0,4)===y).sort((a,b)=>a.date.localeCompare(b.date)).slice(0,10);$('upcoming').innerHTML=list.length?list.map(r=>{const m=meta(r);return `<div class="uprow"><div><b>${esc(m.partner||'取引先')}</b><br><span class="status">${esc(r.date)}</span>${m.note?`<div class="upNote">📝 ${esc(m.note)}</div>`:''}</div><span class="upPrice">${esc(m.price||'価格未入力')}</span></div>`}).join(''):`<div class="empty">${y}年の記録はありません。</div>`}
function setStatus(text){$('status').textContent=text;clearTimeout(setStatus.timer);setStatus.timer=setTimeout(()=>$('status').textContent='',3000)}
function clearForm(){$('rowId').value='';$('partner').value=partners[0];$('price').value='';$('note').value='';$('formTitle').textContent='せり価格を追加';$('deleteBtn').classList.add('hidden')}
function editRow(r){const m=meta(r);$('rowId').value=r.id;$('date').value=r.date;$('partner').value=m.partner||r.partner.replace('カニせり情報:','');$('price').value=m.price||'';$('note').value=m.note||'';$('formTitle').textContent='せり価格を編集';$('deleteBtn').classList.remove('hidden');document.querySelector('.editor').scrollIntoView({behavior:'smooth',block:'center'})}
$('partner').innerHTML=partners.map(p=>`<option>${p}</option>`).join('');$('date').value=fmt(new Date());clearForm();
$('yearSelect').onchange=()=>{view.setFullYear(+$('yearSelect').value);render()};
$('saveBtn').onclick=async()=>{const date=$('date').value,partner=$('partner').value,price=$('price').value.trim(),note=$('note').value.trim();if(!date||!partner||!price)return setStatus('日付・取引先・提示価格を入力してください。');$('saveBtn').disabled=true;try{const id=$('rowId').value||`crab-auction|${date}|${partner}|${Date.now()}`,old=rows.find(r=>r.id===id),body={id,date,partner:'カニせり情報:'+partner,record_type:'crab_auction_price',order_count:0,ship_count:0,sheet_url:'',memo:JSON.stringify({partner,price,note,createdAt:old?meta(old).createdAt||Date.now():Date.now()}),comments:old?.comments||[]};if(old)await api('/orders/rows/'+encodeURIComponent(id),{method:'PUT',body:JSON.stringify(body)});else await api('/orders/rows',{method:'POST',body:JSON.stringify(body)});view=new Date(+date.slice(0,4),+date.slice(5,7)-1,1);await load();clearForm();$('date').value=date;setStatus('保存しました。')}catch(e){setStatus('保存できませんでした。')}finally{$('saveBtn').disabled=false}};
$('deleteBtn').onclick=async()=>{const id=$('rowId').value;if(!id||!confirm('このせり価格を削除しますか？'))return;await api('/orders/rows/'+encodeURIComponent(id),{method:'DELETE'});await load();clearForm();setStatus('削除しました。')};$('clearBtn').onclick=clearForm;
function openComments(r){commentId=r.id;const m=meta(r);$('commentTitle').textContent=`コメント：${r.date} ${m.partner} ${m.price}`;drawComments();$('commentText').value='';$('commentDialog').showModal()}
function drawComments(){const r=rows.find(x=>x.id===commentId),list=r?.comments||[];$('commentList').innerHTML=list.length?list.map((c,i)=>`<div class="comment">${esc(typeof c==='string'?c:c.text||'')}<button type="button" data-i="${i}">×</button></div>`).join(''):'<div class="empty">コメントはありません。</div>';$('commentList').querySelectorAll('button').forEach(b=>b.onclick=()=>deleteComment(+b.dataset.i))}
$('addComment').onclick=async()=>{const text=$('commentText').value.trim(),r=rows.find(x=>x.id===commentId);if(!text||!r)return;const comments=[...(r.comments||[]),{text,createdAt:Date.now()}];await api('/orders/rows/'+encodeURIComponent(r.id)+'/comments',{method:'PUT',body:JSON.stringify({comments})});await load();$('commentText').value='';drawComments()};
async function deleteComment(i){const r=rows.find(x=>x.id===commentId);if(!r)return;const comments=[...(r.comments||[])];comments.splice(i,1);await api('/orders/rows/'+encodeURIComponent(r.id)+'/comments',{method:'PUT',body:JSON.stringify({comments})});await load();drawComments()}
$('closeComment').onclick=()=>$('commentDialog').close();$('prevMonth').onclick=()=>{view.setMonth(view.getMonth()-1);render()};$('nextMonth').onclick=()=>{view.setMonth(view.getMonth()+1);render()};$('thisMonth').onclick=()=>{view=new Date(currentYear,new Date().getMonth(),1);render()};$('refreshBtn').onclick=async()=>{setStatus('更新中…');await load();setStatus('更新しました。')};
(async()=>{try{await load()}catch(e){setStatus('共有データを読み込めませんでした。')}})();