const API='https://flat-disk-51b0.sasaki-8ef.workers.dev';
const partners=['JAいなば','JA米子','JA琴浦','千疋屋','広岡農場'];
const $=id=>document.getElementById(id),cy=new Date().getFullYear();
let rows=[],active=partners[0],mode='this',docIndex=0,pageNo=1,pdf=null,renderSeq=0;
if(window.pdfjsLib)pdfjsLib.GlobalWorkerOptions.workerSrc='https://cdnjs.cloudflare.com/ajax/libs/pdf.js/3.11.174/pdf.worker.min.js';
const esc=s=>String(s||'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot',"'":'&#39;'}[m]));
function year(){return mode==='this'?cy:mode==='last'?cy-1:+$('yearSelect').value||cy}
function meta(r){try{return JSON.parse(r.memo||'{}')}catch(e){return {}}}
function isBoard(r){return r.record_type==='board_file'||r.record_type==='sorting_file'}
function documents(){return rows.filter(r=>{if(!isBoard(r))return false;const m=meta(r);return +m.year===year()&&m.partner===active}).sort((a,b)=>(meta(a).createdAt||0)-(meta(b).createdAt||0))}
function selected(){const d=documents();if(!d.length)return null;docIndex=Math.max(0,Math.min(docIndex,d.length-1));return d[docIndex]}
async function api(path,opt={}){const r=await fetch(API+path,{headers:{'Content-Type':'application/json'},...opt});if(!r.ok)throw new Error(await r.text());return r.json()}
async function load(){const d=await api('/orders/data');rows=d.rows||[]}
function years(){const ys=new Set([cy,cy-1]);rows.filter(isBoard).forEach(r=>{const y=+meta(r).year;if(y)ys.add(y)});const a=[...ys].sort((a,b)=>b-a);$('yearSelect').innerHTML=a.map(y=>`<option value="${y}">${y}年</option>`).join('');if(!a.includes(year()))$('yearSelect').value=cy}
function drawHeader(){$('mode').querySelectorAll('button').forEach(b=>b.classList.toggle('active',b.dataset.mode===mode));$('yearSelect').classList.toggle('hidden',mode!=='all');$('yearLabel').classList.toggle('hidden',mode==='all');$('yearLabel').textContent=year()+'年';$('tabs').innerHTML=partners.map(p=>`<button data-p="${p}" class="${p===active?'active':''}">${p}</button>`).join('');$('tabs').querySelectorAll('button').forEach(b=>b.onclick=()=>{active=b.dataset.p;docIndex=0;pageNo=1;render()})}
function drawDocs(){const d=documents();$('documents').innerHTML=d.length?d.map((r,i)=>`<button class="docTag ${i===docIndex?'active':''}" data-i="${i}">${esc(meta(r).name||'名称未設定')}</button>`).join(''):'<span class="hint">このJAの資料はまだありません。</span>';$('documents').querySelectorAll('button').forEach(b=>b.onclick=()=>{docIndex=+b.dataset.i;pageNo=1;showDocument()});$('docPosition').textContent=d.length?`${docIndex+1} / ${d.length}`:'資料なし';$('prevDoc').disabled=d.length<2;$('nextDoc').disabled=d.length<2}
function bytes(url){const bin=atob(url.slice(url.indexOf(',')+1)),out=new Uint8Array(bin.length);for(let i=0;i<bin.length;i++)out[i]=bin.charCodeAt(i);return out}
async function showDocument(){const r=selected(),viewer=$('viewer');renderSeq++;pdf=null;drawDocs();if(!r){$('sheetTitle').textContent='資料を選択してください';viewer.innerHTML='<div class="empty">資料はまだ登録されていません。</div>';$('pagePosition').textContent='1 / 1';$('prevPage').disabled=$('nextPage').disabled=true;drawComments();return}const m=meta(r);$('sheetTitle').textContent=`${active}｜${m.name||'名称未設定'}`;$('docName').value=m.name||'';const seq=renderSeq;if((m.type||'').includes('pdf')||r.sheet_url.startsWith('data:application/pdf')){viewer.innerHTML='<div class="empty">PDFを読み込み中…</div>';try{if(!window.pdfjsLib)throw new Error('PDF library unavailable');pdf=await pdfjsLib.getDocument({data:bytes(r.sheet_url),cMapUrl:'https://cdnjs.cloudflare.com/ajax/libs/pdf.js/3.11.174/cmaps/',cMapPacked:true,standardFontDataUrl:'https://cdnjs.cloudflare.com/ajax/libs/pdf.js/3.11.174/standard_fonts/',useSystemFonts:true}).promise;if(seq!==renderSeq)return;pageNo=Math.max(1,Math.min(pageNo,pdf.numPages));await drawPdfPage(seq)}catch(e){viewer.innerHTML='<div class="empty">PDFを表示できませんでした。画像形式での再登録をおすすめします。</div>'}}else{const img=document.createElement('img');img.src=r.sheet_url;viewer.innerHTML='';viewer.appendChild(img);pageNo=1;$('pagePosition').textContent='1 / 1';$('prevPage').disabled=$('nextPage').disabled=true}drawComments()}
async function drawPdfPage(seq=renderSeq){if(!pdf)return;const page=await pdf.getPage(pageNo),view=$('viewer'),vp=page.getViewport({scale:1.6}),canvas=document.createElement('canvas');canvas.width=Math.ceil(vp.width);canvas.height=Math.ceil(vp.height);view.innerHTML='';view.appendChild(canvas);await page.render({canvasContext:canvas.getContext('2d'),viewport:vp}).promise;if(seq!==renderSeq)return;$('pagePosition').textContent=`${pageNo} / ${pdf.numPages}`;$('prevPage').disabled=pageNo<=1;$('nextPage').disabled=pageNo>=pdf.numPages;view.scrollTo(0,0)}
function drawComments(){const r=selected(),a=r?.comments||[];$('commentList').innerHTML=a.length?a.map((c,i)=>`<div class="comment">${esc(typeof c==='string'?c:c.text||'')}<button data-i="${i}">×</button></div>`).join(''):'<div class="hint">コメントはありません。</div>';$('commentList').querySelectorAll('button').forEach(b=>b.onclick=async()=>{a.splice(+b.dataset.i,1);await saveComments(r,a)})}
async function saveComments(r,comments){await api('/orders/rows/'+encodeURIComponent(r.id)+'/comments',{method:'PUT',body:JSON.stringify({comments})});await refresh();drawComments()}
async function refresh(){await load();years();drawHeader();drawDocs()}
async function render(){years();drawHeader();drawDocs();await showDocument()}
$('mode').querySelectorAll('button').forEach(b=>b.onclick=()=>{mode=b.dataset.mode;docIndex=0;pageNo=1;render()});$('yearSelect').onchange=()=>{docIndex=0;pageNo=1;render()};
$('prevDoc').onclick=()=>{const d=documents();if(d.length){docIndex=(docIndex-1+d.length)%d.length;pageNo=1;showDocument()}};$('nextDoc').onclick=()=>{const d=documents();if(d.length){docIndex=(docIndex+1)%d.length;pageNo=1;showDocument()}};
$('prevPage').onclick=()=>{if(pdf&&pageNo>1){pageNo--;drawPdfPage()}};$('nextPage').onclick=()=>{if(pdf&&pageNo<pdf.numPages){pageNo++;drawPdfPage()}};
$('uploadBtn').onclick=()=>{const f=$('fileInput').files[0],name=$('docName').value.trim();if(!name)return $('status').textContent='資料名を入力してください。';if(!f)return $('status').textContent='ファイルを選択してください。';const rd=new FileReader();rd.onload=async()=>{try{$('status').textContent='共有保存中…';const id=`board-file|${year()}|${active}|${Date.now()}`,body={id,date:'1900-01-03',partner:'梨掲示板:'+active,record_type:'board_file',order_count:0,ship_count:0,sheet_url:rd.result,memo:JSON.stringify({year:year(),partner:active,name,type:f.type,createdAt:Date.now()}),comments:[]};await api('/orders/rows',{method:'POST',body:JSON.stringify(body)});await refresh();docIndex=documents().length-1;pageNo=1;await showDocument();$('fileInput').value='';$('status').textContent='資料を追加しました。'}catch(e){$('status').textContent='保存できませんでした。画像への変換やファイル容量をご確認ください。'}};rd.readAsDataURL(f)};
$('renameBtn').onclick=async()=>{const r=selected(),name=$('docName').value.trim();if(!r)return $('status').textContent='資料を選択してください。';if(!name)return $('status').textContent='資料名を入力してください。';const m={...meta(r),name};await api('/orders/rows',{method:'POST',body:JSON.stringify({...r,memo:JSON.stringify(m)})});await refresh();await showDocument();$('status').textContent='資料名を変更しました。'};
$('deleteBtn').onclick=async()=>{const r=selected();if(!r)return $('status').textContent='資料を選択してください。';if(!confirm(`「${meta(r).name||'この資料'}」を削除しますか？`))return;await api('/orders/rows/'+encodeURIComponent(r.id),{method:'DELETE'});docIndex=0;pageNo=1;await refresh();await showDocument();$('status').textContent='資料を削除しました。'};
$('addComment').onclick=async()=>{const r=selected(),text=$('commentText').value.trim();if(!r)return $('status').textContent='資料を選択してください。';if(!text)return $('status').textContent='コメントを入力してください。';await saveComments(r,[...(r.comments||[]),{text}]);$('commentText').value='';$('status').textContent='コメントを追加しました。'};
(async()=>{try{await load();await render()}catch(e){$('status').textContent='共有データを読み込めませんでした。'}})();