(()=>{
const API='https://flat-disk-51b0.sasaki-8ef.workers.dev',partners=['JAいなば','JA琴浦','JA米子','千疋屋','広岡農場'],cy=new Date().getFullYear(),$=id=>document.getElementById(id);
let data=[],active='すべて',year=cy,editId='';
const head=document.querySelector('.head'),files=[document.querySelector('.yearBar'),$('tabs'),$('documents'),document.querySelector('.workspace')].filter(Boolean);if(!head)return;
head.querySelector('.sub').textContent='文字だけの投稿と、選果表・日程表などの資料を共有できます。';
const nav=document.createElement('nav');nav.className='boardSwitch';nav.innerHTML='<button class="active" data-v="post">投稿掲示板</button><button data-v="file">資料掲示板</button>';
const pane=document.createElement('section');pane.id='textBoard';pane.innerHTML='<div class="textYear"><div id="textQuick"></div><select id="textYear"></select></div><nav id="textTabs" class="textTabs"></nav><section class="textComposer card"><h3 id="textFormTitle">新しい投稿</h3><label>取引先・出荷元</label><select id="textPartner"></select><label>内容</label><textarea id="textBody" placeholder="共有したい内容を入力してください。文字だけで投稿できます。"></textarea><div class="textActions"><button id="textCancel" class="hidden">編集をやめる</button><button id="textSave" class="textPrimary">投稿する</button></div><div id="textStatus" class="status"></div></section><main id="textFeed" class="textFeed"></main>';
head.after(nav);nav.after(pane);$('textPartner').innerHTML=partners.map(p=>`<option>${p}</option>`).join('');
function show(v){pane.hidden=v!=='post';files.forEach(x=>x.style.display=v==='file'?'':'none');nav.querySelectorAll('button').forEach(b=>b.classList.toggle('active',b.dataset.v===v))}nav.onclick=e=>{const b=e.target.closest('button');if(b)show(b.dataset.v)};show('post');
const esc=s=>String(s||'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
async function api(path,opt={}){const r=await fetch(API+path,{headers:{'Content-Type':'application/json'},...opt});if(!r.ok)throw new Error(await r.text());return r.json()}
function meta(r){try{return JSON.parse(r.memo||'{}')}catch(e){return{}}}
function isPost(r){return r.record_type==='pear_board_post'&&String(r.partner||'').startsWith('梨掲示板:')}
function postYear(r){const m=meta(r);return new Date(m.createdAt||r.date+'T00:00:00').getFullYear()}
function list(){return data.filter(isPost).filter(r=>postYear(r)===year).filter(r=>active==='すべて'||meta(r).partner===active).sort((a,b)=>(meta(b).createdAt||0)-(meta(a).createdAt||0))}
function setStatus(s){$('textStatus').textContent=s;clearTimeout(setStatus.t);setStatus.t=setTimeout(()=>$('textStatus').textContent='',3500)}
async function load(){if(location.protocol==='file:'){data=[{id:'demo',date:new Date().toISOString().slice(0,10),partner:'梨掲示板:JAいなば',record_type:'pear_board_post',memo:JSON.stringify({partner:'JAいなば',text:'文字だけの投稿例です。梨の注意事項を共有できます。',createdAt:Date.now()}),comments:[{text:'確認しました。'}]}]}else{const d=await api('/orders/data');data=d.rows||[]}render()}
function renderYears(){const ys=new Set([cy,cy-1]);data.filter(isPost).forEach(r=>ys.add(postYear(r)));const a=[...ys].sort((x,y)=>y-x);$('textYear').innerHTML=a.map(y=>`<option value="${y}" ${y===year?'selected':''}>${y}年</option>`).join('');$('textQuick').innerHTML=`<button data-y="${cy}" class="${year===cy?'active':''}">今年</button><button data-y="${cy-1}" class="${year===cy-1?'active':''}">去年</button>`;$('textQuick').querySelectorAll('button').forEach(b=>b.onclick=()=>{year=+b.dataset.y;render()})}
function renderTabs(){$('textTabs').innerHTML=['すべて',...partners].map(p=>`<button data-p="${p}" class="${p===active?'active':''}">${p}</button>`).join('');$('textTabs').querySelectorAll('button').forEach(b=>b.onclick=()=>{active=b.dataset.p;render()})}
function dateText(r){const m=meta(r),d=new Date(m.createdAt||r.date+'T00:00:00');return new Intl.DateTimeFormat('ja-JP',{year:'numeric',month:'numeric',day:'numeric',hour:m.createdAt?'2-digit':undefined,minute:m.createdAt?'2-digit':undefined,hour12:false}).format(d)}
function renderFeed(){const a=list();$('textFeed').innerHTML=a.length?a.map(r=>{const m=meta(r),cs=r.comments||[];return `<article class="textPost card" data-id="${esc(r.id)}"><div class="textHead"><div class="textAvatar">${esc(String(m.partner||'梨').slice(0,1))}</div><div class="textMeta"><b>${esc(m.partner||'出荷元')}</b><span>${esc(dateText(r))}</span></div><button data-a="edit">編集</button><button data-a="delete" class="textDelete">削除</button></div><div class="textContent">${esc(m.text)}</div><div class="textComments"><div>${cs.length?cs.map(c=>`<p>${esc(typeof c==='string'?c:c.text||'')}</p>`).join(''):'<span class="status">コメントはありません。</span>'}</div><div class="textCommentForm"><input placeholder="コメントを入力"><button data-a="comment">コメント</button></div></div></article>`}).join(''):`<div class="textEmpty">${year}年の${active==='すべて'?'投稿':active+'の投稿'}はまだありません。</div>`;$('textFeed').querySelectorAll('.textPost').forEach(c=>{const id=c.dataset.id;c.querySelector('[data-a="edit"]').onclick=()=>startEdit(id);c.querySelector('[data-a="delete"]').onclick=()=>remove(id);c.querySelector('[data-a="comment"]').onclick=()=>comment(id,c.querySelector('input').value.trim())})}
function render(){renderYears();renderTabs();renderFeed()}
function clear(){editId='';$('textBody').value='';$('textFormTitle').textContent='新しい投稿';$('textSave').textContent='投稿する';$('textCancel').classList.add('hidden')}
function startEdit(id){const r=data.find(x=>x.id===id),m=meta(r);if(!r)return;editId=id;$('textPartner').value=m.partner||partners[0];$('textBody').value=m.text||'';$('textFormTitle').textContent='投稿を編集';$('textSave').textContent='変更を保存';$('textCancel').classList.remove('hidden');pane.scrollIntoView({behavior:'smooth'})}
$('textYear').onchange=()=>{year=+$('textYear').value;render()};$('textCancel').onclick=clear;
$('textSave').onclick=async()=>{const p=$('textPartner').value,text=$('textBody').value.trim();if(!text)return setStatus('内容を入力してください。');const old=data.find(x=>x.id===editId),was=!!editId,now=Date.now(),id=editId||`pear-board|${now}|${Math.random().toString(36).slice(2,7)}`,body={id,date:new Date().toISOString().slice(0,10),partner:'梨掲示板:'+p,record_type:'pear_board_post',order_count:0,ship_count:0,sheet_url:'',memo:JSON.stringify({partner:p,text,createdAt:meta(old).createdAt||now}),comments:old?.comments||[]};$('textSave').disabled=true;try{if(was)await api('/orders/rows/'+encodeURIComponent(id),{method:'PUT',body:JSON.stringify(body)});else await api('/orders/rows',{method:'POST',body:JSON.stringify(body)});clear();active=p;year=cy;await load();setStatus(was?'更新しました。':'投稿しました。')}catch(e){setStatus('投稿できませんでした。')}finally{$('textSave').disabled=false}};
async function remove(id){if(!confirm('この投稿を削除しますか？'))return;try{await api('/orders/rows/'+encodeURIComponent(id),{method:'DELETE'});await load();setStatus('削除しました。')}catch(e){setStatus('削除できませんでした。')}}
async function comment(id,text){if(!text)return;const r=data.find(x=>x.id===id),comments=[...(r?.comments||[]),{text,createdAt:Date.now()}];try{await api('/orders/rows/'+encodeURIComponent(id)+'/comments',{method:'PUT',body:JSON.stringify({comments})});await load()}catch(e){setStatus('コメントを追加できませんでした。')}}
const style=document.createElement('style');style.textContent='.boardSwitch{display:flex;gap:8px;margin-top:14px}.boardSwitch button,#textQuick button,.textTabs button,.textComposer button,.textPost button{min-height:42px;border:1px solid var(--line);border-radius:9px;background:#fff;padding:9px 12px;font:inherit;font-weight:800;cursor:pointer}.boardSwitch .active,#textQuick .active,.textTabs .active{background:var(--green)!important;border-color:var(--green)!important;color:#fff}.boardSwitch button{flex:1}#textBoard{margin-top:12px}.textYear{display:flex;justify-content:space-between;gap:10px;padding:10px 12px;background:#fff;border:1px solid var(--line);border-radius:12px}.textTabs,#textQuick,.textActions{display:flex;gap:7px;flex-wrap:wrap}.textTabs{margin:10px 0}.textComposer{padding:14px;margin-bottom:14px}.textComposer h3{margin:0 0 8px}.textComposer label{display:block;margin:9px 0 5px;color:var(--muted);font-size:12px;font-weight:800}.textComposer select,.textComposer textarea,.textCommentForm input{width:100%;border:1px solid var(--line);border-radius:9px;padding:10px;font:inherit}.textComposer textarea{min-height:110px;resize:vertical}.textActions{margin-top:10px}.textPrimary{margin-left:auto;background:var(--green)!important;color:#fff}.textFeed{display:grid;gap:12px}.textPost{overflow:hidden}.textHead{display:flex;align-items:center;gap:9px;padding:12px}.textAvatar{display:grid;place-items:center;width:40px;height:40px;border-radius:50%;background:var(--green-soft);color:#26704d;font-weight:900}.textMeta{display:grid;flex:1}.textMeta span{font-size:12px;color:var(--muted)}.textHead button{min-height:34px;padding:5px 9px;font-size:12px}.textDelete{color:#a33}.textContent{padding:0 14px 13px;white-space:pre-wrap;line-height:1.65}.textComments{border-top:1px solid var(--line);padding:10px 14px;background:#fafafa}.textComments p{margin:0 0 6px;padding:8px 10px;border-radius:9px;background:#e5f2fc;white-space:pre-wrap}.textCommentForm{display:grid;grid-template-columns:1fr auto;gap:7px}.textEmpty{padding:28px;text-align:center;background:#fff;border:1px dashed #ccc;border-radius:14px;color:var(--muted)}@media(max-width:600px){.textYear{flex-direction:column}.textTabs{display:grid;grid-template-columns:1fr 1fr}.textTabs button:first-child{grid-column:1/-1}.textHead{flex-wrap:wrap}.textCommentForm{grid-template-columns:1fr}}';document.head.appendChild(style);
load().catch(()=>setStatus('共有データを読み込めませんでした。'));
})();